/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 17
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 15
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_l_bracket = 1,
  sym_r_bracket = 2,
  sym_l_brace = 3,
  sym_r_brace = 4,
  sym_new_line = 5,
  sym_name_text = 6,
  sym_comment_text = 7,
  sym_body_text = 8,
  sym_source_file = 9,
  sym_block = 10,
  sym_name_mark = 11,
  sym_writer_mark = 12,
  aux_sym_source_file_repeat1 = 13,
  aux_sym_block_repeat1 = 14,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_l_bracket] = "l_bracket",
  [sym_r_bracket] = "r_bracket",
  [sym_l_brace] = "l_brace",
  [sym_r_brace] = "r_brace",
  [sym_new_line] = "new_line",
  [sym_name_text] = "name_text",
  [sym_comment_text] = "comment_text",
  [sym_body_text] = "body_text",
  [sym_source_file] = "source_file",
  [sym_block] = "block",
  [sym_name_mark] = "name_mark",
  [sym_writer_mark] = "writer_mark",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_l_bracket] = sym_l_bracket,
  [sym_r_bracket] = sym_r_bracket,
  [sym_l_brace] = sym_l_brace,
  [sym_r_brace] = sym_r_brace,
  [sym_new_line] = sym_new_line,
  [sym_name_text] = sym_name_text,
  [sym_comment_text] = sym_comment_text,
  [sym_body_text] = sym_body_text,
  [sym_source_file] = sym_source_file,
  [sym_block] = sym_block,
  [sym_name_mark] = sym_name_mark,
  [sym_writer_mark] = sym_writer_mark,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_l_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_r_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_l_brace] = {
    .visible = true,
    .named = true,
  },
  [sym_r_brace] = {
    .visible = true,
    .named = true,
  },
  [sym_new_line] = {
    .visible = true,
    .named = true,
  },
  [sym_name_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_text] = {
    .visible = true,
    .named = true,
  },
  [sym_body_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_name_mark] = {
    .visible = true,
    .named = true,
  },
  [sym_writer_mark] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '[') ADVANCE(8);
      if (lookahead == ']') ADVANCE(9);
      if (lookahead == '{') ADVANCE(10);
      if (lookahead == '}') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == ']') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == '}') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 3:
      if (('[' <= lookahead && lookahead <= ']') ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(18);
      END_STATE();
    case 4:
      if (('[' <= lookahead && lookahead <= ']') ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(14);
      END_STATE();
    case 5:
      if (('[' <= lookahead && lookahead <= ']') ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(16);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '[') ADVANCE(8);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == '{') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '}') ADVANCE(18);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_l_bracket);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_r_bracket);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_l_brace);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_r_brace);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_new_line);
      if (lookahead == '\n') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_name_text);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_name_text);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment_text);
      if (lookahead == '\\') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment_text);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_body_text);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '\\') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_body_text);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(18);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_l_bracket] = ACTIONS(1),
    [sym_r_bracket] = ACTIONS(1),
    [sym_l_brace] = ACTIONS(1),
    [sym_r_brace] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(14),
    [sym_block] = STATE(2),
    [sym_name_mark] = STATE(4),
    [sym_writer_mark] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_block_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_l_bracket] = ACTIONS(5),
    [sym_l_brace] = ACTIONS(7),
    [sym_new_line] = ACTIONS(9),
    [sym_body_text] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_block] = STATE(3),
    [sym_name_mark] = STATE(4),
    [sym_writer_mark] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_block_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_l_bracket] = ACTIONS(5),
    [sym_l_brace] = ACTIONS(7),
    [sym_new_line] = ACTIONS(9),
    [sym_body_text] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym_block] = STATE(3),
    [sym_name_mark] = STATE(4),
    [sym_writer_mark] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_block_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_l_bracket] = ACTIONS(17),
    [sym_l_brace] = ACTIONS(20),
    [sym_new_line] = ACTIONS(23),
    [sym_body_text] = ACTIONS(26),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      sym_l_bracket,
    ACTIONS(7), 1,
      sym_l_brace,
    ACTIONS(29), 1,
      sym_new_line,
    ACTIONS(31), 1,
      sym_body_text,
    STATE(5), 3,
      sym_name_mark,
      sym_writer_mark,
      aux_sym_block_repeat1,
  [18] = 5,
    ACTIONS(33), 1,
      sym_l_bracket,
    ACTIONS(36), 1,
      sym_l_brace,
    ACTIONS(39), 1,
      sym_new_line,
    ACTIONS(41), 1,
      sym_body_text,
    STATE(5), 3,
      sym_name_mark,
      sym_writer_mark,
      aux_sym_block_repeat1,
  [36] = 2,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    ACTIONS(46), 4,
      sym_l_bracket,
      sym_l_brace,
      sym_new_line,
      sym_body_text,
  [46] = 2,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    ACTIONS(50), 4,
      sym_l_bracket,
      sym_l_brace,
      sym_new_line,
      sym_body_text,
  [56] = 1,
    ACTIONS(52), 4,
      sym_l_bracket,
      sym_l_brace,
      sym_new_line,
      sym_body_text,
  [63] = 1,
    ACTIONS(54), 4,
      sym_l_bracket,
      sym_l_brace,
      sym_new_line,
      sym_body_text,
  [70] = 1,
    ACTIONS(56), 4,
      sym_l_bracket,
      sym_l_brace,
      sym_new_line,
      sym_body_text,
  [77] = 1,
    ACTIONS(58), 4,
      sym_l_bracket,
      sym_l_brace,
      sym_new_line,
      sym_body_text,
  [84] = 2,
    ACTIONS(60), 1,
      sym_r_bracket,
    ACTIONS(62), 1,
      sym_name_text,
  [91] = 2,
    ACTIONS(64), 1,
      sym_r_brace,
    ACTIONS(66), 1,
      sym_comment_text,
  [98] = 1,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
  [102] = 1,
    ACTIONS(70), 1,
      sym_r_bracket,
  [106] = 1,
    ACTIONS(72), 1,
      sym_r_brace,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 18,
  [SMALL_STATE(6)] = 36,
  [SMALL_STATE(7)] = 46,
  [SMALL_STATE(8)] = 56,
  [SMALL_STATE(9)] = 63,
  [SMALL_STATE(10)] = 70,
  [SMALL_STATE(11)] = 77,
  [SMALL_STATE(12)] = 84,
  [SMALL_STATE(13)] = 91,
  [SMALL_STATE(14)] = 98,
  [SMALL_STATE(15)] = 102,
  [SMALL_STATE(16)] = 106,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_name_mark, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_writer_mark, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_name_mark, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_writer_mark, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [68] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sf(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "sf",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
